import React from 'react'

const products = [
    {
        id: 1,
        name: "Chocolate Chunk Brownie",
        category: "Brownies",
        description: "A gooey treat for the chocoholics!",
        price: 220,
        currency: "Rs",
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT7YCrKXxObfSfkwE5LBe4rq3LdudVu9fXbUw&s",
    },
    {
        id: 2,
        name: "Nutella Brownie",
        category: "Brownies",
        description: "Nutella frosting on a super moist brownie!",
        price: 220,
        currency: "Rs",
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT7YCrKXxObfSfkwE5LBe4rq3LdudVu9fXbUw&s",
    },
    {
        id: 3,
        name: "Mars Chocolate Brownie",
        category: "Brownies",
        description: "Pure chocolate icing with imported caramel!",
        price: 220,
        currency: "Rs",
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT7YCrKXxObfSfkwE5LBe4rq3LdudVu9fXbUw&s",
    },
    {
        id: 4,
        name: "Belgian Malt Brownie",
        category: "Brownies",
        description: "Imported chocolate frosting on a soft brownie!",
        price: 220,
        currency: "Rs",
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT7YCrKXxObfSfkwE5LBe4rq3LdudVu9fXbUw&s",
    },
    {
        id: 5,
        name: "Cadbury Brownie",
        category: "Brownies",
        description: "Cadbury chocolate frosting on a super moist brownie!",
        price: 220,
        currency: "Rs",
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT7YCrKXxObfSfkwE5LBe4rq3LdudVu9fXbUw&s",
    },
    {
        id: 6,
        name: "Hershey’s Fudge Brownie",
        category: "Brownies",
        description: "Scrumptious brownie made with imported cocoa and lots of Hershey's",
        price: 220,
        currency: "Rs",
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT7YCrKXxObfSfkwE5LBe4rq3LdudVu9fXbUw&s",
    },
    {
        id: 7,
        name: "Peanut Butter Stack Brownie",
        category: "Brownies",
        description: "Light milk chocolate, Buttery caramel & chocolate brownie with a peanut butter crunch!",
        price: 220,
        currency: "Rs",
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT7YCrKXxObfSfkwE5LBe4rq3LdudVu9fXbUw&s",
    },
    // --- Cakes ---
    {
        id: 8,
        name: "Chocolate Fudge Cake",
        category: "Cakes",
        description: "Rich chocolate cake layered with fudge frosting.",
        price: 1500,
        currency: "Rs",
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSZpzr5ZFbZCdOOU47NqqfQKAjAb48gbumZHg&s",
    },
    {
        id: 9,
        name: "Red Velvet Cake",
        category: "Cakes",
        description: "Classic red velvet with cream cheese frosting.",
        price: 1800,
        currency: "Rs",
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSZpzr5ZFbZCdOOU47NqqfQKAjAb48gbumZHg&s",
    },
    {
        id: 10,
        name: "Black Forest Cake",
        category: "Cakes",
        description: "Layers of chocolate sponge with cream and cherries.",
        price: 1700,
        currency: "Rs",
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSZpzr5ZFbZCdOOU47NqqfQKAjAb48gbumZHg&s",
    },
    {
        id: 11,
        name: "Vanilla Bean Cake",
        category: "Cakes",
        description: "Moist vanilla cake with creamy vanilla frosting.",
        price: 1600,
        currency: "Rs",
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSZpzr5ZFbZCdOOU47NqqfQKAjAb48gbumZHg&s",
    },
    {
        id: 12,
        name: "Lemon Drizzle Cake",
        category: "Cakes",
        description: "Tangy lemon sponge with a sweet glaze.",
        price: 1400,
        currency: "Rs",
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSZpzr5ZFbZCdOOU47NqqfQKAjAb48gbumZHg&s",
    },
    {
        id: 13,
        name: "Strawberry Shortcake",
        category: "Cakes",
        description: "Light sponge layered with strawberries and cream.",
        price: 1700,
        currency: "Rs",
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSZpzr5ZFbZCdOOU47NqqfQKAjAb48gbumZHg&s",
    },
    {
        id: 14,
        name: "Carrot Cake",
        category: "Cakes",
        description: "Moist carrot sponge with cream cheese frosting.",
        price: 1600,
        currency: "Rs",
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSZpzr5ZFbZCdOOU47NqqfQKAjAb48gbumZHg&s",
    },
    {
        id: 15,
        name: "Coffee Walnut Cake",
        category: "Cakes",
        description: "Coffee sponge with walnut crunch and frosting.",
        price: 1650,
        currency: "Rs",
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSZpzr5ZFbZCdOOU47NqqfQKAjAb48gbumZHg&s",
    },
    {
        id: 16,
        name: "Pineapple Upside Down Cake",
        category: "Cakes",
        description: "Classic cake with caramelized pineapple topping.",
        price: 1500,
        currency: "Rs",
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSZpzr5ZFbZCdOOU47NqqfQKAjAb48gbumZHg&s",
    },
    {
        id: 17,
        name: "Cheesecake",
        category: "Cakes",
        description: "Creamy cheesecake with buttery biscuit base.",
        price: 1800,
        currency: "Rs",
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSZpzr5ZFbZCdOOU47NqqfQKAjAb48gbumZHg&s",
    },
    {
        id: 18,
        name: "Oreo Cake",
        category: "Cakes",
        description: "Chocolate cake layered with Oreo frosting.",
        price: 1750,
        currency: "Rs",
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSZpzr5ZFbZCdOOU47NqqfQKAjAb48gbumZHg&s",
    },
    {
        id: 19,
        name: "Mango Mousse Cake",
        category: "Cakes",
        description: "Soft sponge filled with fresh mango mousse.",
        price: 1700,
        currency: "Rs",
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSZpzr5ZFbZCdOOU47NqqfQKAjAb48gbumZHg&s",
    },
    {
        id: 20,
        name: "Chocolate Truffle Cake",
        category: "Cakes",
        description: "Dark chocolate sponge with rich truffle layers.",
        price: 1900,
        currency: "Rs",
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSZpzr5ZFbZCdOOU47NqqfQKAjAb48gbumZHg&s",
    },
    {
        id: 21,
        name: "Fruit Cake",
        category: "Cakes",
        description: "Classic sponge cake with mixed dried fruits.",
        price: 1600,
        currency: "Rs",
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSZpzr5ZFbZCdOOU47NqqfQKAjAb48gbumZHg&s",
    },
    {
        id: 22,
        name: "Banana Cake",
        category: "Cakes",
        description: "Soft banana sponge with light frosting.",
        price: 1500,
        currency: "Rs",
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSZpzr5ZFbZCdOOU47NqqfQKAjAb48gbumZHg&s",
    },
    {
        id: 23,
        name: "Blueberry Cake",
        category: "Cakes",
        description: "Moist vanilla sponge with blueberries inside.",
        price: 1750,
        currency: "Rs",
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSZpzr5ZFbZCdOOU47NqqfQKAjAb48gbumZHg&s",
    },
    {
        id: 24,
        name: "Marble Cake",
        category: "Cakes",
        description: "Swirled vanilla and chocolate sponge cake.",
        price: 1550,
        currency: "Rs",
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSZpzr5ZFbZCdOOU47NqqfQKAjAb48gbumZHg&s",
    },
    {
        id: 25,
        name: "Rainbow Cake",
        category: "Cakes",
        description: "Colorful sponge layers with vanilla frosting.",
        price: 2000,
        currency: "Rs",
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSZpzr5ZFbZCdOOU47NqqfQKAjAb48gbumZHg&s",
    },
    {
        id: 26,
        name: "Ferrero Rocher Cake",
        category: "Cakes",
        description: "Chocolate sponge layered with Ferrero Rocher cream.",
        price: 2200,
        currency: "Rs",
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSZpzr5ZFbZCdOOU47NqqfQKAjAb48gbumZHg&s",
    },

    // --- Cookies ---
    {
        id: 27,
        name: "Chocolate Chip Cookie",
        category: "Cookies",
        description: "Classic soft cookie loaded with chocolate chips.",
        price: 120,
        currency: "Rs",
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS3cVQICsBL6_lMmdIaSwcYUdneIwvX0naFIQ&s",
    },
    {
        id: 28,
        name: "Double Chocolate Cookie",
        category: "Cookies",
        description: "Rich cocoa cookie with extra chocolate chunks.",
        price: 150,
        currency: "Rs",
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS3cVQICsBL6_lMmdIaSwcYUdneIwvX0naFIQ&s",
    },
    {
        id: 29,
        name: "Oatmeal Raisin Cookie",
        category: "Cookies",
        description: "Healthy oats and juicy raisins baked fresh.",
        price: 100,
        currency: "Rs",
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS3cVQICsBL6_lMmdIaSwcYUdneIwvX0naFIQ&s",
    },
    {
        id: 30,
        name: "Peanut Butter Cookie",
        category: "Cookies",
        description: "Chewy peanut butter cookie with nutty goodness.",
        price: 140,
        currency: "Rs",
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS3cVQICsBL6_lMmdIaSwcYUdneIwvX0naFIQ&s",
    },
    {
        id: 31,
        name: "White Chocolate Macadamia Cookie",
        category: "Cookies",
        description: "Premium white chocolate and crunchy macadamia nuts.",
        price: 180,
        currency: "Rs",
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS3cVQICsBL6_lMmdIaSwcYUdneIwvX0naFIQ&s",
    },
    {
        id: 32,
        name: "Triple Chocolate Cookie",
        category: "Cookies",
        description: "Dark, milk, and white chocolate in one cookie.",
        price: 160,
        currency: "Rs",
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS3cVQICsBL6_lMmdIaSwcYUdneIwvX0naFIQ&s",
    },
    {
        id: 33,
        name: "Almond Crunch Cookie",
        category: "Cookies",
        description: "Buttery cookie with roasted almond chunks.",
        price: 170,
        currency: "Rs",
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS3cVQICsBL6_lMmdIaSwcYUdneIwvX0naFIQ&s",
    },
    {
        id: 34,
        name: "Coconut Delight Cookie",
        category: "Cookies",
        description: "Soft cookie filled with shredded coconut flavor.",
        price: 150,
        currency: "Rs",
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS3cVQICsBL6_lMmdIaSwcYUdneIwvX0naFIQ&s",
    },
    // --- Cupcakes ---
    {
        id: 35,
        name: "Ferrero Rocher Cupcake",
        category: "Cupcakes",
        description: "Lots & lots of hazelnut chocolate!",
        price: 250,
        image: "https://layers.pk/wp-content/uploads/2021/11/Chocolate-Hazelnut.jpg",
    },
    {
        id: 36,
        name: "Red Velvet Cupcake",
        category: "Cupcakes",
        description: "Crème cheese, Red velvety sponge & lots of love!",
        price: 250,
        image: "https://layers.pk/wp-content/uploads/2021/11/Chocolate-Hazelnut.jpg",
    },
    {
        id: 37,
        name: "Belgian Malt Cupcake",
        category: "Cupcakes",
        description: "Made from premium Belgian chocolate!",
        price: 250,
        image: "https://layers.pk/wp-content/uploads/2021/11/Chocolate-Hazelnut.jpg",
    },
    {
        id: 38,
        name: "Chocolate Hazelnut Cupcake",
        category: "Cupcakes",
        description: "Milk chocolate with hazelnut chocolate drippings!",
        price: 250,
        image: "https://layers.pk/wp-content/uploads/2021/11/Chocolate-Hazelnut.jpg",
    },
    {
        id: 39,
        name: "Classic Chocolate Cupcake",
        category: "Cupcakes",
        description: "Milk chocolate crème & lots of love!",
        price: 250,
        image: "https://layers.pk/wp-content/uploads/2021/11/Chocolate-Hazelnut.jpg",
    },
    {
        id: 40,
        name: "Original Malt Cupcake",
        category: "Cupcakes",
        description: "Malt mixed with crème cheese, Light & lovely!",
        price: 250,
        image: "https://layers.pk/wp-content/uploads/2021/11/Chocolate-Hazelnut.jpg",
    },
    {
        id: 41,
        name: "M&M Cupcake",
        category: "Cupcakes",
        description: "Crème milk chocolate with M&M's crushed inside!",
        price: 250,
        image: "https://layers.pk/wp-content/uploads/2021/11/Chocolate-Hazelnut.jpg",
    },
    {
        id: 42,
        name: "Chocolate Cream Cheese Cupcake",
        category: "Cupcakes",
        description: "Ideal mixture of chocolate & crème!",
        price: 250,
        image: "https://layers.pk/wp-content/uploads/2021/11/Chocolate-Hazelnut.jpg",
    },
    {
        id: 43,
        name: "Swiss Dark Chocolate Cupcake",
        category: "Cupcakes",
        description: "Dark crème swiss chocolate frosting!",
        price: 250,
        image: "https://layers.pk/wp-content/uploads/2021/11/Chocolate-Hazelnut.jpg",
    },
    {
        id: 44,
        name: "Salted Caramel Cupcake",
        category: "Cupcakes",
        description: "Salted caramel, Crème cheese & moist vanilla sponge!",
        price: 250,
        image: "https://layers.pk/wp-content/uploads/2021/11/Chocolate-Hazelnut.jpg",
    },
    {
        id: 45,
        name: "After 8 Mint Cupcake",
        category: "Cupcakes",
        description: "Belgian chocolate with a 'Hint of Mint'!",
        price: 250,
        image: "https://layers.pk/wp-content/uploads/2021/11/Chocolate-Hazelnut.jpg",
    },
    {
        id: 46,
        name: "Milk Chocolate Cupcake",
        category: "Cupcakes",
        description: "Nothing but soft & classic milk chocolate!",
        price: 250,
        image: "https://layers.pk/wp-content/uploads/2021/11/Chocolate-Hazelnut.jpg",
    },
    {
        id: 47,
        name: "Nutella Cupcake",
        category: "Cupcakes",
        description: "Made with pure 100% Nutella chocolate.",
        price: 250,
        image: "https://layers.pk/wp-content/uploads/2021/11/Chocolate-Hazelnut.jpg",
    },
    {
        id: 48,
        name: "Matcha Cupcake",
        category: "Cupcakes",
        description: "Organic matcha blended in crème cheese with a pinch of imported dark chocolate on top!",
        price: 250,
        image: "https://layers.pk/wp-content/uploads/2021/11/Chocolate-Hazelnut.jpg",
    },
    {
        id: 49,
        name: "Cotton Candy Cupcake",
        category: "Cupcakes",
        description: "Fluffy rainbow cotton candy flavored swirl on a moist vanilla cupcake",
        price: 250,
        image: "https://layers.pk/wp-content/uploads/2021/11/Chocolate-Hazelnut.jpg",
    },
    {
        id: 50,
        name: "Keylime Cupcake",
        category: "Cupcakes",
        description: "Super moist white chocolate mizzle with organic lemon on the top",
        price: 250,
        image: "https://layers.pk/wp-content/uploads/2021/11/Chocolate-Hazelnut.jpg",
    },
    {
        id: 51,
        name: "Lotus Biscoff Cupcake",
        category: "Cupcakes",
        description: "Artistically made using imported cream cheese & lotus biscoff spread on soft vanilla sponge!",
        price: 250,
        image: "https://layers.pk/wp-content/uploads/2021/11/Chocolate-Hazelnut.jpg",
    },
    {
        id: 52,
        name: "Oreo Cookie Cupcake",
        category: "Cupcakes",
        description: "Classic Oreo goodness blended with moist chocolate sponge.",
        price: 250,
        image: "https://layers.pk/wp-content/uploads/2021/11/Chocolate-Hazelnut.jpg",
    },
    {
        id: 53,
        name: "Peanut Butter Cupcake",
        category: "Cupcakes",
        description: "Rich peanut butter frosting swirled on top of moist chocolate sponge.",
        price: 250,
        image: "https://layers.pk/wp-content/uploads/2021/11/Chocolate-Hazelnut.jpg",
    },
    {
        id: 54,
        name: "Caramel Crunch Cupcake",
        category: "Cupcakes",
        description: "Vanilla sponge topped with caramel frosting & crunchy bits!",
        price: 250,
        image: "https://layers.pk/wp-content/uploads/2021/11/Chocolate-Hazelnut.jpg",
    },
    // --- Desserts ---
    {
        id: 55,
        name: "Nutella Sundae",
        category: "Desserts",
        description: "A heavenly sundae made with layers of Nutella & whipped cream.",
        price: 350,
        image: "https://layers.pk/wp-content/uploads/2021/11/nutella-sundae-copy.jpg",
    },
    {
        id: 56,
        name: "Lotus Biscoff Sundae",
        category: "Desserts",
        description: "Delicious sundae made with Lotus Biscoff spread, cream & crunchy toppings.",
        price: 350,
        image: "https://layers.pk/wp-content/uploads/2021/11/nutella-sundae-copy.jpg",
    },
    {
        id: 57,
        name: "Brownie Sundae",
        category: "Desserts",
        description: "Soft brownie chunks served with ice cream & chocolate drizzle.",
        price: 350,
        image: "https://layers.pk/wp-content/uploads/2021/11/nutella-sundae-copy.jpg",
    },
    {
        id: 58,
        name: "Red Velvet Sundae",
        category: "Desserts",
        description: "A creamy sundae made with red velvet cake & cream cheese frosting.",
        price: 350,
        image: "https://layers.pk/wp-content/uploads/2021/11/nutella-sundae-copy.jpg",
    },
    {
        id: 59,
        name: "Classic Ice Cream Sundae",
        category: "Desserts",
        description: "Classic sundae with vanilla ice cream, chocolate sauce & sprinkles.",
        price: 300,
        image: "https://layers.pk/wp-content/uploads/2021/11/nutella-sundae-copy.jpg",
    },
    {
        id: 60,
        name: "Strawberry Sundae",
        category: "Desserts",
        description: "Refreshing strawberry sundae with whipped cream & berry drizzle.",
        price: 320,
        image: "https://layers.pk/wp-content/uploads/2021/11/nutella-sundae-copy.jpg",
    },
    {
        id: 61,
        name: "Caramel Crunch Sundae",
        category: "Desserts",
        description: "Sundae topped with caramel drizzle & crunchy bits.",
        price: 340,
        image: "https://layers.pk/wp-content/uploads/2021/11/nutella-sundae-copy.jpg",
    },
    {
        id: 62,
        name: "Chocolate Fudge Sundae",
        category: "Desserts",
        description: "Chocolate ice cream with thick fudge sauce & whipped cream.",
        price: 360,
        image: "https://layers.pk/wp-content/uploads/2021/11/nutella-sundae-copy.jpg",
    },
    {
        id: 63,
        name: "Oreo Sundae",
        category: "Desserts",
        description: "Vanilla ice cream blended with crushed Oreo cookies.",
        price: 330,
        image: "https://layers.pk/wp-content/uploads/2021/11/nutella-sundae-copy.jpg",
    },
    {
        id: 64,
        name: "Peanut Butter Sundae",
        category: "Desserts",
        description: "A rich sundae topped with peanut butter & chocolate swirl.",
        price: 350,
        image: "https://layers.pk/wp-content/uploads/2021/11/nutella-sundae-copy.jpg",
    },
    {
        id: 65,
        name: "Mango Sundae",
        category: "Desserts",
        description: "Seasonal mango sundae with whipped cream & fruit toppings.",
        price: 340,
        image: "https://layers.pk/wp-content/uploads/2021/11/nutella-sundae-copy.jpg",
    },
    // --- Mini Donuts ---
    {
        id: 66,
        name: "Cotton Candy Donut",
        category: "Mini Donuts",
        description: "A fluffy donut topped with cotton candy sweetness.",
        price: 180,
        image: "https://layers.pk/wp-content/uploads/2024/08/Cotton-Candy-9.jpg",
    },
    {
        id: 67,
        name: "Chocolate Glazed Donut",
        category: "Mini Donuts",
        description: "Soft donut coated in rich chocolate glaze.",
        price: 180,
        image: "https://layers.pk/wp-content/uploads/2024/08/Cotton-Candy-9.jpg",
    },
    {
        id: 68,
        name: "Strawberry Sprinkle Donut",
        category: "Mini Donuts",
        description: "Strawberry frosting topped with colorful sprinkles.",
        price: 180,
        image: "https://layers.pk/wp-content/uploads/2024/08/Cotton-Candy-9.jpg",
    },
    {
        id: 69,
        name: "Lotus Biscoff Donut",
        category: "Mini Donuts",
        description: "Mini donut topped with Lotus Biscoff spread & crumbs.",
        price: 200,
        image: "https://layers.pk/wp-content/uploads/2024/08/Cotton-Candy-9.jpg",
    },
    {
        id: 70,
        name: "Nutella Donut",
        category: "Mini Donuts",
        description: "Mini donut filled with gooey Nutella & drizzled on top.",
        price: 200,
        image: "https://layers.pk/wp-content/uploads/2024/08/Cotton-Candy-9.jpg",
    },
    {
        id: 71,
        name: "Caramel Crunch Donut",
        category: "Mini Donuts",
        description: "Donut topped with caramel glaze & crunchy bits.",
        price: 190,
        image: "https://layers.pk/wp-content/uploads/2024/08/Cotton-Candy-9.jpg",
    },
    {
        id: 72,
        name: "Oreo Mini Donut",
        category: "Mini Donuts",
        description: "Mini donut topped with Oreo cream & crushed cookies.",
        price: 190,
        image: "https://layers.pk/wp-content/uploads/2024/08/Cotton-Candy-9.jpg",
    },
    {
        id: 73,
        name: "Vanilla Glazed Donut",
        category: "Mini Donuts",
        description: "Classic vanilla glaze on soft fluffy mini donut.",
        price: 170,
        image: "https://layers.pk/wp-content/uploads/2024/08/Cotton-Candy-9.jpg",
    },
    {
        id: 74,
        name: "Peanut Butter Donut",
        category: "Mini Donuts",
        description: "Mini donut topped with peanut butter & chocolate drizzle.",
        price: 200,
        image: "https://layers.pk/wp-content/uploads/2024/08/Cotton-Candy-9.jpg",
    },
    {
        id: 75,
        name: "Red Velvet Donut",
        category: "Mini Donuts",
        description: "Mini donut with red velvet glaze & cream cheese topping.",
        price: 200,
        image: "https://layers.pk/wp-content/uploads/2024/08/Cotton-Candy-9.jpg",
    },
    {
        id: 76,
        name: "Blueberry Donut",
        category: "Mini Donuts",
        description: "Mini donut with blueberry glaze and drizzle.",
        price: 190,
        image: "https://layers.pk/wp-content/uploads/2024/08/Cotton-Candy-9.jpg",
    },
    {
        id: 77,
        name: "Pistachio Donut",
        category: "Mini Donuts",
        description: "Mini donut with pistachio glaze and nuts on top.",
        price: 200,
        image: "https://layers.pk/wp-content/uploads/2024/08/Cotton-Candy-9.jpg",
    },
    {
        id: 78,
        name: "Mango Glazed Donut",
        category: "Mini Donuts",
        description: "Tropical mango glaze over soft fluffy donut.",
        price: 180,
        image: "https://layers.pk/wp-content/uploads/2024/08/Cotton-Candy-9.jpg",
    },
    {
        id: 79,
        name: "Coffee Donut",
        category: "Mini Donuts",
        description: "Coffee flavored glaze for coffee lovers.",
        price: 190,
        image: "https://layers.pk/wp-content/uploads/2024/08/Cotton-Candy-9.jpg",
    },
    {
        id: 80,
        name: "Matcha Green Tea Donut",
        category: "Mini Donuts",
        description: "Donut glazed with earthy matcha green tea.",
        price: 200,
        image: "https://layers.pk/wp-content/uploads/2024/08/Cotton-Candy-9.jpg",
    },
    {
        id: 81,
        name: "Almond Crunch Donut",
        category: "Mini Donuts",
        description: "Donut topped with almond slices and glaze.",
        price: 190,
        image: "https://layers.pk/wp-content/uploads/2024/08/Cotton-Candy-9.jpg",
    },
    {
        id: 82,
        name: "Honey Glazed Donut",
        category: "Mini Donuts",
        description: "Classic honey glaze for a sweet finish.",
        price: 170,
        image: "https://layers.pk/wp-content/uploads/2024/08/Cotton-Candy-9.jpg",
    },
    {
        id: 83,
        name: "Coconut Donut",
        category: "Mini Donuts",
        description: "Donut topped with coconut flakes and glaze.",
        price: 190,
        image: "https://layers.pk/wp-content/uploads/2024/08/Cotton-Candy-9.jpg",
    },
    {
        id: 84,
        name: "Raspberry Donut",
        category: "Mini Donuts",
        description: "Raspberry glaze with fruity drizzle.",
        price: 190,
        image: "https://layers.pk/wp-content/uploads/2024/08/Cotton-Candy-9.jpg",
    },
    // --- Sundaes ---
    {
        id: 86,
        name: "Chocolate Fudge Sundae",
        category: "Sundaes",
        description: "Rich chocolate ice cream layered with hot fudge and whipped cream.",
        price: 350,
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR9PiHHm6I6EyBfbHL-8lfN5nW7I85h0og7zQ&s",
    },
    {
        id: 87,
        name: "Strawberry Sundae",
        category: "Sundaes",
        description: "Vanilla ice cream topped with strawberry syrup and fresh berries.",
        price: 330,
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR9PiHHm6I6EyBfbHL-8lfN5nW7I85h0og7zQ&s",
    },
    {
        id: 88,
        name: "Caramel Crunch Sundae",
        category: "Sundaes",
        description: "Caramel sauce, crunchy toffee bits, and creamy vanilla ice cream.",
        price: 360,
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR9PiHHm6I6EyBfbHL-8lfN5nW7I85h0og7zQ&s",
    },
    {
        id: 89,
        name: "Oreo Sundae",
        category: "Sundaes",
        description: "Oreo crumbles with vanilla ice cream, chocolate syrup, and cream.",
        price: 370,
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR9PiHHm6I6EyBfbHL-8lfN5nW7I85h0og7zQ&s",
    },
    {
        id: 90,
        name: "Nutella Sundae",
        category: "Sundaes",
        description: "Vanilla ice cream topped with Nutella drizzle and hazelnuts.",
        price: 380,
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR9PiHHm6I6EyBfbHL-8lfN5nW7I85h0og7zQ&s",
    },
    {
        id: 91,
        name: "Lotus Biscoff Sundae",
        category: "Sundaes",
        description: "Lotus Biscoff spread and crumbs layered with creamy ice cream.",
        price: 400,
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR9PiHHm6I6EyBfbHL-8lfN5nW7I85h0og7zQ&s",
    },
    {
        id: 92,
        name: "Brownie Sundae",
        category: "Sundaes",
        description: "Chunks of gooey brownie served with ice cream and fudge.",
        price: 390,
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR9PiHHm6I6EyBfbHL-8lfN5nW7I85h0og7zQ&s",
    },
    {
        id: 93,
        name: "Mango Sundae",
        category: "Sundaes",
        description: "Tropical mango syrup over creamy vanilla ice cream.",
        price: 340,
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR9PiHHm6I6EyBfbHL-8lfN5nW7I85h0og7zQ&s",
    },
    {
        id: 94,
        name: "Coffee Sundae",
        category: "Sundaes",
        description: "Coffee-flavored ice cream with chocolate drizzle and cream.",
        price: 350,
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR9PiHHm6I6EyBfbHL-8lfN5nW7I85h0og7zQ&s",
    },
    {
        id: 95,
        name: "Pistachio Sundae",
        category: "Sundaes",
        description: "Nutty pistachio ice cream layered with whipped cream and syrup.",
        price: 370,
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR9PiHHm6I6EyBfbHL-8lfN5nW7I85h0og7zQ&s",
    },

];

export default products;